### ISSUE TITLE
Swipe only on the left and disable right swipe

### ISSUE THREAD

**Issue by dajver** [romannurik/Android-SwipeToDismiss#31] opened 2016-02-12 20:19 UTC
Hi! How can I do this? Can you help me please?

I know that I have to do some stuff in SwipeDismissListViewTouchListener in the onTouch method, but I don't know what... Help please ^_^

**Comment by cricket007** [comment] 2016-02-15 23:10
Possible duplicate of #12

**Closed** 2019-05-16 18:14 UTC
